require("prototypes.functions")
require("prototypes.entity.belt-particles")
require("prototypes.entity.belt-explosions")
require("prototypes.entity.belt-remnants")
require("prototypes.entity.belt-updates")
require("prototypes.item.belt-icons")